imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: [default, applog]
    handlers:
        main:
            type:         fingers_crossed
            action_level: notice
            handler:      mongo
        console:
            type:  console
        mongo:
            type: mongo
            level: error
            mongo:
                id: mongolog
                database: %mongo_database%
                collection: %mongo_log_collection%
        mongo_app:
            type: mongo
            level: info
            mongo:
                id: mongolog
                database: %mongo_database%
                collection: %mongo_applog_collection%
            channels: applog