imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    channels: [default, applog]
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        mongo:
            type:   mongo
            level:  error
            mongo:
                id: mongolog
                database: %mongo_database%
                collection: %mongo_log_collection%
            channels: default
        mongo_app:
            type: mongo
            level: info
            mongo:
                id: mongolog
                database: %mongo_database%
                collection: %mongo_applog_collection%
            channels: applog

swiftmailer:
    delivery_address: %email_debug_address%
    disable_delivery: %email_debug_disabled%
