services:
    mongo_client:
            class: MongoClient
            arguments: [%mongo_url%]

    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments:
          - @mongo_client
          - {database: %mongo_database%, collection: %mongo_session_collection% }

    mongolog:
        class: Doctrine\MongoDB\Connection
        factory_service: doctrine_mongodb.odm.log_connection
        factory_method: getMongoClient

    simple_dom_parser:
        class: Sunra\PhpSimple\HtmlDomParser
