services:
    app.form.registration:
        class: AppBundle\Form\Type\User\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.http_grabber:
        class: AppBundle\Service\HttpGrabber
        arguments: [@guzzle.client.lostfilm]

    app.parser:
        class: AppBundle\Service\Parser
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - @monolog.logger.applog
            - @simple_dom_parser

    app.sender:
        class: AppBundle\Service\Sender
        arguments:
            - @templating
            - @doctrine.odm.mongodb.document_manager
            - @monolog.logger.applog
            - @app.sender.mail
            - @app.sender.telegram

    app.sender.mail:
        class: AppBundle\Service\Sender\MailSender
        arguments:
            - @mailer
            - @monolog.logger.applog
            - %from_email%
            - %from_email_sender%

    app.sender.telegram:
        class: AppBundle\Service\Sender\TelegramSender
        arguments:
            - @shaygan.telegram_bot_api
            - @monolog.logger.applog

    app.telegram_reciver:
        class: AppBundle\Service\TelegramReciver
        arguments:
            - %shaygan_telegram_bot_api.config%
            - @shaygan.telegram_bot_api
            - @monolog.logger.applog
            - @doctrine.odm.mongodb.document_manager
