parameters:

services:
    mongo_client:
            class: MongoClient
            arguments: [%mongo_url%]

    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments:
          - @mongo_client
          - {database: %mongo_database%, collection: %mongo_session_collection% }

    app.http_grabber:
        class: AppBundle\Service\HttpGrabber
        arguments: [@guzzle.client.lostfilm]

    app.rss_parser:
        class: AppBundle\Service\RssParser
        arguments: [@doctrine.odm.mongodb.document_manager, @logger]

    simple_dom_parser:
        class: Sunra\PhpSimple\HtmlDomParser

    app.mail_sender:
        class: AppBundle\Service\MailSender
        arguments: [@swiftmailer.mailer, @templating, @doctrine.odm.mongodb.document_manager]