services:
    app.form.registration:
        class: AppBundle\Form\Type\User\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.sender:
        class: AppBundle\Service\Sender
        arguments:
            - @templating
            - @doctrine.odm.mongodb.document_manager
            - @monolog.logger.applog
            - @app.sender.mail
            - @app.sender.telegram

    app.listener.new_showw:
        class: AppBundle\Listener\NewShowsListener
        arguments:
            - @app.sender
        tags:
            - { name: kernel.event_listener, event: app.new_show, method: onNewShow }

    app.sender.mail:
        class: AppBundle\Service\Sender\MailSender
        arguments:
            - @mailer
            - @monolog.logger.applog
            - %from_email%
            - %from_email_sender%

    app.sender.telegram:
        class: AppBundle\Service\Sender\TelegramSender
        arguments:
            - @shaygan.telegram_bot_api
            - @monolog.logger.applog

    app.telegram_reciver:
        class: AppBundle\Service\TelegramReciver
        arguments:
            - %shaygan_telegram_bot_api.config%
            - @shaygan.telegram_bot_api
            - @monolog.logger.applog
            - @doctrine.odm.mongodb.document_manager

    app.grabber.lostfilm:
        class: AppBundle\Service\Grabber\LosftfilmGrabber
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - @simple_dom_parser
            - @monolog.logger.applog
            - @guzzle.client.lostfilm
            - @event_dispatcher

    app.grabber.animedia:
        class: AppBundle\Service\Grabber\AnimediaGrabber
        arguments:
            - @doctrine.odm.mongodb.document_manager
            - @simple_dom_parser
            - @monolog.logger.applog
            - @guzzle.client.animedia
            - @event_dispatcher
